### PR TITLE
Create LFCSP-8-1EP_2x3mm_Pitch0.5mm.kicad_mod

### PR DESCRIPTION
**Pull request by evanshultz**
Image:
image

Passes all current official, released KLC script checks and also has the ref des text on F.Fab.

See page 13 of http://www.analog.com/media/en/technical-documentation/data-sheets/AD8218.pdf and also http://www.analog.com/media/en/technical-documentation/application-notes/AN-772.pdf.

Most of the design is pulled from AN-772. Pads are 0.28mm wide as shown in Table II. Pad length is 0.55mm as found from the 0.4mm pin length + 0.1mm + 0.05mm from Table I. Pad 9 is the same width as the exposed thermal pin but not quite as tall to maintain the 0.25mm metal-to-metal clearance as mentioned on page 4.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Pin-1 should be at top-left as per KLC 6.2

**Comment by evanshultz** [comment]
Thanks for catching that. Updated.

**Comment by evanshultz** [comment]
Also, the ref des text on F.Fab is outside the F.Fab rectangle, but I think we stick with the standard 1x1mm size unless we choose an expected max ref des char length. It appears 3-4 chars will fit inside the rectangle. While "REF**" is too long, maybe it will be "T1" or "Q1". Or it could be "TR3503". We just don't know and it seems to be that we're still covering quite a large number of ref des possibilities.

**Comment by SchrodingersGat** [comment]
Please add keyword tags - otherwise good to merge :)

**Pull request merged**
