### PR TITLE
Create LFCSP-8_2x2mm_Pitch0.5mm.kicad_mod

### PR DESCRIPTION
**Pull request by evanshultz**
Image:
image

Passes all current official, released KLC script checks and also has the ref des text on F.Fab.

See http://www.analog.com/media/en/package-pcb-resources/package/pkg_pdf/lfcspcp/cp_8_6.pdf and also http://www.analog.com/media/en/technical-documentation/application-notes/AN-772.pdf.

Most of the design is pulled from AN-772. Pads are 0.28mm tall as shown in Table II. Pad width is 0.75mm as found from the 0.6mm pin length + 0.1mm + 0.05mm from Table I.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@evanshultz looks pretty good!

1. Please add keyword description tags
1. The filename should be changed to match the footprint name (you have a `-` where it should be a `_`)

Thanks :)

**Comment by evanshultz** [comment]
1. Done.
2. Already done, but Travis didn't pick it up.

BTW, where are the tags/keywords even used?

**Comment by evanshultz** [comment]
I see. In Pcbnew, when placing a footprint I can enter something in the box at the top and then search by keyword.

**Comment by SchrodingersGat** [comment]
Please fix name as shown below and then we can merge :)

2017-03-17 09_44_31-create lfcsp-8_2x2mm_pitch0 5mm kicad_mod by evanshultz pull request 4 kica

**Comment by evanshultz** [comment]
Again, I know Travis shows this as a problem but the latest commit is already correct. I caught this myself and fixed it before your first comment. Check it out.

**Comment by SchrodingersGat** [comment]
This is not just a Travis thing - if you click on the "Files Changed" tab it shows that the filename does not have an underscore in the correct place...

**Comment by evanshultz** [comment]
Not for me:
image

And I know I fixed it with commit https://github.com/KiCad/Housings_CSP.pretty/pull/4/commits/87ba5f14cce8fac3ec9e63a66127a42698475ed6.

Am I really missing something so basic?

**Comment by SchrodingersGat** [comment]
That's the name of the module *inside* the file!

Please change the actual file-name to match.

Currently `LFCSP-8-2x2mm_Pitch0.5mm`
Change -> `LFCSP-8_2x2mm_Pitch0.5mm`

**Comment by evanshultz** [comment]
Ah! Finally I see what you mean. Thanks for your patience.

**Comment by SchrodingersGat** [comment]
Thanks! :)

**Pull request merged**
