### PR TITLE
Add 16 and 24 pin LFCSP (lead frame CSP) packages

### PR DESCRIPTION
**Pull request by rivimey**
Based on drawings from Analog Devices for the AD4940 Buffer chips.
Not much experience with this, so there are probably things to improve!

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@rivimey thanks for the contribution. There are a few things to improve here so that it complies with our [Library Conventions](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention)

**Note: We have a much newer [KLC](https://github.com/SchrodingersGat/kicad-library/wiki/KLC) which you should read through too** - this will be "live" very soon.

Please refer to the automated checker script output:

capture

You can download and run these scripts yourself, if you like - https://github.com/KiCad/kicad-library-utils

This touches on most of the issues, but I'll run through some of them in general terms:

### Silkscreen
For SMT parts, the silkscreen should not be "under" the part once it is loaded. It should especially not be placed over the pads. The silkscreen should be entirely visible once the part is on the board, and should provide a pin-1 marker.

### Fab Layer
The outline of part should be added to the F.Fab (Front Fabrication) layer. Pin-1 on F.Fab is indicated by a 45 degree bevel on the corner next to pin-1

### Naming
The footprint name should include dimensions and pitch. Have a look at the other part in this library and all the parts in for e.g:

* https://github.com/KiCad/Housings_QFP.pretty
* https://github.com/KiCad/Housings_SSOP.pretty

So for e.g. `LFCSP-24_4x4mm_Pitch0.5mm`

### Line width and Text Size
We have some conventions for line width and text size - please conform to these

### Courtyard
Please draw a courtyard around the part with an 0.25mm clearance, on the F.CrtYd Layer, line width 0.05mm

### Second RefDes
Please add a second reference designator to the F.Fab layer @ (0,0). You add a text item with the value "%R" to achieve this.

**Note: The second RefDes does not have to be exactly 1mm in size like the silkscreen requirement - it can be smaller if needed to fit inside the outline of the part**

### Documentation
Please fill out documentation fields for each footprint.
`Doc` field should contain description and perhaps a datasheet if you have a link to one
`Keywords` field should contain a few descriptive keywords (look at other components e.g. QFP for examples)

Here is an example of how one of your footprints would look:

capture
3d

Let me know if you have any questions about any of this. Thanks!

**Comment by rivimey** [comment]
I haven't renamed the LFCSP-40 fps because I can no longer remember what they represent :(
They are a something, but not sure exactly what ... should I delete them or leave them as-is?

**Comment by rivimey** [comment]
The courtyard clearance test doesn't make sense to me.. it complains even though clearance is definitely >= 0.25mm now.

**Comment by jkriege2** [comment]
The current scripts under Travis are a bit buggy. Please ensure that the courtyard is as required by the new versions of the KLC with 0.25mm clearance from the package outline or pad outline (whichever is farther out). We will then  check by hand ;-)

**Comment by rivimey** [comment]
Well, the courtyard is I believe adequate -- perhaps even a bit over 0.25mm as I was increasing it, trying to get the test to pass. I think it will do. Would you have a look and see if you agree?

**Comment by SchrodingersGat** [comment]
Hi @rivimey generally very good, one thing I would still change:

capture

Please remove the silkscreen line that would sit underneath the package (highlighted below)

**Comment by poeschlr** [comment]
@rivimey Would you care to make this last modification?

**Comment by evanshultz** [comment]
@rivimey Sorry for the spam but we'd like to know if you can make the change requested above.

In addition, I think there might be some changes to the footprint names we can consider. Existing footprints have names like `LFCSP-8_2x2mm_Pitch0.5mm`, so looking at the [AD4940 datasheet](http://www.analog.com/media/en/technical-documentation/data-sheets/ADA4940-1_4940-2.pdf) I would suggest `LFCSP-16-1EP_3x3mm_Pitch0.5mm` and `LFCSP-24-1EP_4x4mm_Pitch0.5mm`.

Thanks again for making these footprints and contributing to KiCad!

**Comment by SchrodingersGat** [comment]
@rivimey 



In preparation for the v5 KiCad software release, we are marking this repository as "legacy" and not accepting any new pull requests. These footprints have been moved to the new `kicad-footprints` repository at https://github.com/kicad/kicad-footprints

Sorry for the inconvenience, however this change will make the contribution process easier for everyone.

Please resubmit your contribution over at the new repository :)

**Pull request closed without merging**
