### PR TITLE
Add LFCSP-VQ-48-1EP_7x7mm_Pitch0.5mm

### PR DESCRIPTION
**Pull request by evanshultz**
I realized when looking at https://github.com/KiCad/SMD_Packages.pretty/issues/20 there was a 7x7mm 40 pin LFCSP package. I couldn't find this anywhere online, but it was close enough to this package that I decided to go ahead and make it.

Things to consider:
- I'm not sure what the VQ means but ADI uses it to describe this package.
- The pin 1 marker on F.Fab is something new since this has beveled corners; thoughts on it?

Datasheet: http://www.analog.com/media/en/technical-documentation/data-sheets/AD7951.pdf

Image:
image

Ultra Librarian image:
image

### CODE REVIEW

**Comment by evanshultz** [comment]
Can this be merged?

**Comment by evanshultz** [comment]
Can I get a review, please?

**Comment by evanshultz** [comment]
Review, please.

**Comment by evanshultz** [comment]
Can someone review this, please?

**Comment by SchrodingersGat** [comment]
@evanshultz is this part specific to Analog? Or can it be used generically for parts from multiple manufacturers?

**Comment by evanshultz** [comment]
While I've only seen it used by ADI, here are two examples where multiple packaging houses provide this package:
- https://www.amkor.com/go/packaging/all-packages/microleadframeandreg-/microleadframe-mlf--mlp--qfn-quad-flat-no-lead
- http://docs-europe.electrocomponents.com/webdocs/1151/0900766b81151747.pdf

So I say generic.

**Comment by SchrodingersGat** [comment]
Alright, thanks for your contribution :)

**Pull request merged**
