### PR TITLE
Create LFCSP-16-1EP_3x3mm_Pitch0.5mm.kicad_mod

### PR DESCRIPTION
**Pull request by evanshultz**
Create footprint for ADI CP-16-22 package. Datasheet: http://www.analog.com/media/en/technical-documentation/data-sheets/AD5689_5687.pdf

It's using the newer thermal pad style, with one Cu pad and several Paste rectangles.

Image:
image

ADI doesn't put the footprint in the datasheets or [package drawing](http://www.analog.com/media/en/package-pcb-resources/package/pkg_pdf/lfcspcp/cp_16_22.pdf) file for some absurd reason. Instead, they thinks it's best that the only way to see their recommended footprints is for one to download the 161MB [Ultra Librarian viewer](http://www.analog.com/en/design-center/packaging-quality-symbols-footprints/symbols-and-footprints/AD5697R.html), which requires 2GB disk space to install, after which you can download the binary footprint file and view it. And yes, I went to all the trouble of doing that to see their footprint, and then found it didn't match an otherwise similar QFN footprint. So here we are. Honestly, ADI, could you have made this task, easy with any other manufacturer I've ever seen, any more unpleasant?? OK, I'm done. For now.

### CODE REVIEW

**Comment by evanshultz** [comment]
Since the footprint isn't in the datasheet, here are screenshots from Ultra Librarian to confirm the design:
image
image

Any issues with this footprint?

**Comment by evanshultz** [comment]
Can this be merged?

**Comment by evanshultz** [comment]
Can I get a review, please?

**Comment by evanshultz** [comment]
@jkriege2 Are you still reviewing and merging? How about this one? Similar pad styles as we just discussed.

**Comment by jkriege2** [comment]
looks good to me!
JAN

**Pull request merged**
